### ISSUE TITLE
feature: expose RegEx

### ISSUE THREAD

**Issue by atomGit** [PerfectSlayer/scrollupfolder#27]
wondering if you might consider exposing the RegEx for segmenting the URL for better customization?

**Comment by PerfectSlayer** [comment]
Hi @atomGit 

The function which computes the URLs is not only a RegEx. It is based on Firefox APIs.
You could have a look to [the function](https://github.com/PerfectSlayer/scrollupfolder/blob/release/chrome/content/overlay.js#L815) or [the API computing segments](https://github.com/PerfectSlayer/scrollupfolder/blob/release/chrome/content/overlay.js#L841).

So I will be hard to expose this feature.. Perhaps the best solution for you is to fork the source to customize the algorithm to fit your needs. But if you have ideas to improve it, feel free to share so I could integrate it for everyone.

Regards.

**Comment by atomGit** [comment]
@PerfectSlayer - thanks for the reply
i was wanting to split URL parameters at the "&" char - that is actually useful sometimes...
`example.com/?aaa&bbb
example.com/?aaa
example.com/`

**Comment by PerfectSlayer** [comment]
Hum, did you have a look at the first part of the issue #23 ?
It looks like this match what you want, isn't it?

**Comment by atomGit** [comment]
not exactly - i'm not interested in in incrementing the variable - see my example again ...
`example.com/?aaa&bbb

example.com/?aaa

example.com/`

**Comment by PerfectSlayer** [comment]
I barely see the difference between:
- http://www.example.com/page?var1=8&var2=9
- http://www.example.com/page?var1=8
- http://www.example.com/page  
and: 
- example.com/?aaa&bbb
- example.com/?aaa
- example.com/

Where aaa and bbb are parameter names without value. Why the "Parse in key-value blocks" doesn't did the trick?

**Comment by atomGit** [comment]
ah, yes, you're right - there is no difference - both examples are the same
/?a=1&b=2
/?a=1
/

i thought that enabling the "parse get vars..." would allow this, but it doesn't

**Comment by PerfectSlayer** [comment]
Nope, for the moment, the option only strips the get vars in one block.
The issue #23 deals with this improvement but the original reporter doesn't seemto be involve anymore.

The main question that remains before I implement it is: does it make sens to cut URL var by var?
I mean, there is no logic in var order so it will be no logic in URL displayed in panel..

**Comment by atomGit** [comment]
i messed up - sorry - although splitting at the & char could be useful in some cases, what i meant was to split at the # char

a lot of times you may open a URL to, for example, a forum thread that points to a particular post (anchor tag) and it would be nice to trim that in some cases...
/this#that
/this

**Comment by PerfectSlayer** [comment]
Sorry for the delay, I was moving my home…

So you want to strip the anchor only? I could be easy to do.
Would you like I have a look at it?

**Comment by atomGit** [comment]
moving your hom.... OH i get it!  you mean like this...
https://www.youtube.com/watch?v=xI3O_frrQN4

sure, if you have dev version i can test that would be great

**Comment by PerfectSlayer** [comment]
Here is a [dev preview version with anchor parsing support](http://hardcoding.free.fr/scrollupfolder_4.2.12_strip-anchor.xpi).
Give it a try then give me your feedback :wink: 

P.S.: Yeah, it was too heavy, I just buy a new one :dizzy_face:

**Comment by atomGit** [comment]
it works, but it's a bit strange that it took a little fiddling to get it to work at first - i loaded up a page, enabled the option to segment # chars and it didn't work, as i sort of expected, however even a page reload didn't work.  upon loading a new page however, it worked as expected and then when i closed and re-opened the original it worked there also, so i guess all is OK

perhaps more importantly, it is probably highly likely that the wife/GF will be pestering you to get things done around your new home, in which case this might come in handy...
http://kuukunen.net/pics/he_will_fix_it.jpg

**Comment by PerfectSlayer** [comment]
The strange behavior is due to the fact I keep computed URLs are cached by tab for the current page.
So enabling the option and check the current page will not work. You will have to change page or open a new tab to enjoy the new behavior.

Anyway, if everything works file, I will make a public release and upload it to AMO and babelzilla.
Don't forget to re-install the AMO version to have the future updates!

Right, actually she is flooding my todolist with no-tech tasks (like fixing radiators, installing window curtains, …) :cry:

**Comment by atomGit** [comment]
seems to work fine - thanks for your work :)
take care!

**Comment by PerfectSlayer** [comment]
The new version is live on AMO! Feel free to leave review if you have an account :angel:
