### ISSUE TITLE
FF freezes for ftp protocol

### ISSUE THREAD

**Issue by atomGit** [PerfectSlayer/scrollupfolder#29]
go to an ftp site, like ftp.mozilla.org (you may have to nav to something beyond the root dir), then click in the address bar to give it keyboard focus - FF freezes

tested on a completely fresh (empty) profile with only SUF installed
FF 40.0.2
SUF 5.0.0
Win 7

**Comment by PerfectSlayer** [comment]
Thanks for your report! 
I'll try it tomorrow as soon as I grab my computer to test. 

I keep you updated. 
Best regards.

**Comment by PerfectSlayer** [comment]
Ok, I confirm the freeze. Sorry for the trouble.
I have another bug to fix and I will make a new release soon.

Thanks!

**Comment by atomGit** [comment]
no, thank you :)
