### ISSUE TITLE
Error/Broken with Private Window

### ISSUE THREAD

**Issue by Peuj** [PerfectSlayer/scrollupfolder#30]
HI,

When I open Firefox with a new private window (directly from the Window Taskbar) I get this error message:

TypeError: window is null
Trace de la pile :
close@resource://gre/modules/commonjs/toolkit/loader.js -> resource://scrollupfolder-at-omni-dot-n0ne-dot-org/scrollupfolder/lib/urlpanel.js:72:6
fr.hardcoding.scrollupfolder.urlpanel.ensureClose@resource://gre/modules/commonjs/toolkit/loader.js -> resource://scrollupfolder-at-omni-dot-n0ne-dot-org/scrollupfolder/lib/main.js:313:4
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
tabEmit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/tabs/tab-firefox.js:245:25
tabEventListener@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/tabs/tab-firefox.js:299:23
@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/tabs/tab-firefox.js:318:39
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:123:45
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
frameMessageReceived@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/remote/parent.js:152:32

I think the problem is on the Addon-sdk side but at least you know. :)

**Comment by PerfectSlayer** [comment]
Thanks for the report! 
You're right. The log points my add-on: scrollupfolder/lib/urlpanel.js:72:6

I will check this tonight as soon as I get back home. I'll keep you updated. 
Best regards.

**Comment by PerfectSlayer** [comment]
Hi,

I just run some tests and I can't reproduce. I tried with Firefox 40 and 43 without success.
I have Firefox opened, I right click on the taskbar and open a new private window without issue.

Could you give me more details? Does it always happened for you?
Thanks.

**Comment by Peuj** [comment]
Hi,

To reproduce the problem, you must not have Firefox opened before to open a private window.
And yes, this way, I always reproduce the problem.

**Comment by PerfectSlayer** [comment]
Thanks for the details.
I finished to reproduce the bug and fix it. Sorry for the trouble.

I will release a new version tonight with two fixes and locales updated.
It will be available as soon as Mozilla approves it. Thanks!
