### ISSUE TITLE
Add an option to choose left or middle click 

### ISSUE THREAD

**Issue by Peuj** [PerfectSlayer/scrollupfolder#31]
Hi,

Is it possible to add an option the choose left or middle click to go on the URL?
On laptop without a mouse it's not really convenient.

Thanks

**Comment by PerfectSlayer** [comment]
Hi,
If you choose to use the left click to go on the URL, how do you do type an URL in urlbar ?

Regards.

**Comment by Peuj** [comment]
Hi,

You're right, I didn't use scrollupfolder this way, I never needed to select the URL to modify it.

Maybe you could add an option like:
 * Alt + Left Click => go to URL | Left Click => select URL
or
 * Left Click => go to URL | Alt + Left Click => select URL

Not really a mandatory request anyway. :)

Thanks

**Comment by PerfectSlayer** [comment]
It looks complicated!
If you are ready to press one key and one mouse button (alt + click), why not simply click on the URL and press Enter? :smile:

**Comment by Peuj** [comment]
My idea was to propose the already existing mode:
 - Alt + Left Click => go to URL | Left Click => select URL

or **another new mode** (the one I would like to use)

 - Left Click => go to URL | Alt + Left Click => select URL

But if you feel it's too complicated no worry and you don't loose your time for this.

Thanks

**Comment by PerfectSlayer** [comment]
I close the issue as mouse event are no more accessible through the WebExtension API.
However, thanks for your suggestion!
