### ISSUE TITLE
parsing GET vars not working?

### ISSUE THREAD

**Issue by atomGit** [PerfectSlayer/scrollupfolder#32]
i'm expecting `https://voat.co/search/findsubverse?q=news&d=true` to go to `https://voat.co/search/findsubverse?q=news`, but instead it goes to `https://voat.co/search/findsubverse`

**Comment by PerfectSlayer** [comment]
Hi @atomGit 

The only thing that parse get vars does is trimming the question mark and all the vars.
Without you will have the following entries:
`https://voat.co/search/findsubverse?q=news&d=true`
`https://voat.co/search/`
And with parse get var enabled, you have one more entry:
`https://voat.co/search/findsubverse?q=news&d=true`
`https://voat.co/search/findsubverse`
`https://voat.co/search/`

I'm always wondering if cutting vars is interesting? I mean, there is no order between vars in URL, so how to know which one removes in first? And if you have 5 vars, do you add 5 entries more?

**Comment by atomGit** [comment]
you know, i think i brought this up before - my memory is crap and i'm sorry if this the case

of course you are right regarding the order of the variables, but i would say this; if it is only a simple matter of adding '&' to your RegEx, and performance isn't an issue, then why not?

you could make it hinge on the current GET option without having to add a new option

whatever you decide, it isn't really important to me personally, just useful in some cases

**Comment by PerfectSlayer** [comment]
Yes, this question was already posted :wink: 

Not a performance issue. But I don't want the user who navigates with keyboard is annoyed with too much entries... 
Nevertheless, the URL rewriting is often used to mask GET vars and create fake directories instead (ie www.myblog.com?article=1 becomes www.myblog/article/1) so It should be logic to parse GET vars as you said.

**Comment by PerfectSlayer** [comment]
Hi @atomGit 
I finally add this feature.
Check here for the implementation: https://github.com/PerfectSlayer/scrollupfolder/commit/48448d788eafc2868407f921b3c94df0ac0c057c#diff-16b7d75b70953cbf4755508170f2f24cR562

I'll release this version on AMO soon I guess :wink:
