### ISSUE TITLE
Not wokring with FF 43.0.3

### ISSUE THREAD

**Issue by PerfectSlayer** [PerfectSlayer/scrollupfolder#34]
Original issue report from ar11x on [AMO](https://addons.mozilla.org/fr/firefox/addon/scroll-up-folder/reviews/770854/)

> Not wokring with FF 43.0.3
>
> The extension keep pop up the new UI notification,
> and user need to click the address button manually.

**Comment by PerfectSlayer** [comment]
I tried to reproduce on Firefox 43.0.3 on Windows 64b:
* Fresh install + reboots
* Fresh install + reboots always in private mode

I never had UI notification bug :disappointed:

**Comment by ar1xwe** [comment]
Sorry my bad. I am using my own "Shortcut" so it never pop up.

I make my shortcut direct to Ctrl + L it works.
but I still wanna give you some suggestions.

Why not trigger this extension by navigation ?
1. Focus Url bar
2. Navigate
3. Pop up the notification of Scroll Up Folder

It's really useful for surfing on some particular websites,
but ALT is not the best solution.Maybe a new option !?

btw ~ I must apologize about my English. It's horrible loool, Hope you understand what I meant.

**Comment by PerfectSlayer** [comment]
For information, there is two default shortcuts for urlbar: ```CTRL+L``` or ```F4```.

If I understand you well, you suggest to open the panel with the list of ulrs when you focus the urlbar using a shortcut ? If I do this, people can no more use the "awesomebar".

For example,
* I'm at the following page: ```https://github.com/PerfectSlayer/scrollupfolder/issues/34```
* I go to the urlbar with ```CTRL+L```
* I remove the last ```issues/34``` characters from the current url
* The "awesomebar" opens and propose different urls than Scroll Up Folder. For example ```https://github.com/PerfectSlayer/scrollupfolder/wiki``` or ```https://github.com/PerfectSlayer/scrollupfolder/tree/master``` (which all start by the current urlbar value)

So I use ```ALT``` key to open url panel to offer "alt"ernative urls. If I open it by default, I think I will block user from using the default Firefox behavior.

And thanks for updating your previous review :ok_hand:

**Comment by Gitoffthelawn** [comment]
FWIW, `F4` does not seem to work anymore.  `Ctrl+L` works fine.

**Comment by PerfectSlayer** [comment]
@Gitoffthelawn Woops, I mean ```F6```. 
There is also ```ALT```+```D``` which opens the url panel at the same time :wink:

**Comment by ar1xwe** [comment]
Okay ! Thanks.
Problem solved !
That's not a bug...My brain has bug looool...

**Comment by PerfectSlayer** [comment]
No problem. You're welcome.
