### ISSUE TITLE
Minor Issue: Icon missing from about:addons

### ISSUE THREAD

**Issue by Gitoffthelawn** [PerfectSlayer/scrollupfolder#35]
Minor issue: the icon is missing from about:addons (Add-ons Manager).

Normally, Firefox assigns a default icon when the extension has no icon.  But for some reason, this extension gets a blank icon.

Not a big deal, but I thought you may want to know.

**Comment by PerfectSlayer** [comment]
Hi @Gitoffthelawn
Thanks for your report. I'll have a look tonight. 

From memory, I removed one of the two icons (48px and 64px) because it became deprecated. Maybe it's related.

**Comment by Gitoffthelawn** [comment]
You're welcome.  Thank *YOU* for the great extension!

I took a quick look at the DOM, and for the extension icon, it shows `src=data/images/icon.png`.

That file is present in the xpi, but I think you may need a `chrome:` prefix and perhaps a specifier for the parent folder.

**Comment by PerfectSlayer** [comment]
You're welcome too :wink: 

Hum, I guess I'm doing right but according to [the documentation](https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/package_json#icon) (there is always a bug) it seems to have an issue in ```jpm``` (the tool used to build the add-on): mozilla-jetpack/jpm#197

So, I'll try to make a fix in the build add-on (not in the add-on manifest add-on itself).
I keep you updated!

**Comment by Gitoffthelawn** [comment]
Sounds great!

BTW, you've created a fantastic extension.  I regularly find it very useful.

Before writing this, I thought "what can I suggest to make it even better", and you know what?  I couldn't think of anything substantial!

My only quip is that the middle button on my pointing device is hard to press, so I don't really like using it to load the URL.  But I can't think of a better alternative.  If you have any ideas, I'm all ears, but it makes perfect sense how it currently behaves.

**Comment by PerfectSlayer** [comment]
Very thanks you! It's the perfect sentences if you would like to make a review on AMO :innocent:

No really good solution for you. In my case, I use keyboard shortcuts when I use laptop or I'm lazy to move my hand up to the mouse.

By the way, I fix my tool and send the update to AMO. You are now quoted in the changelog. Thanks for your report :wink:
