### ISSUE TITLE
Addon does not load when private browsing is enabled by default

### ISSUE THREAD

**Issue by PerfectSlayer** [PerfectSlayer/scrollupfolder#37]
#### What steps will reproduce the problem?
1. Enable private browsing by default (browser.privatebrowsing.autostart to true in about:config)
2. Start Firefox

#### What is the expected behavior? What do you see instead?
The extension does not load in the first browser window (the window when Firefox launches).
The next windows opened will work as expected (ie the addon will be loaded).

#### Could you describe us your platform?
* Firefox version: Any version
* Operating system: Any OS

#### Anything else to add to help us?
It's [an already known addonsdk issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1224863).
The bug was [reported by Mozfan on AMO](https://addons.mozilla.org/fr/firefox/addon/scroll-up-folder/reviews/812068/).

**Comment by PerfectSlayer** [comment]
I just found how to fix the issue in addonsdk.
I will post it on Github this weekend when I have tested it more.

**Comment by quiproquo** [comment]
Thank you very much for your detailed answer on AMO!
If ever you still need some inspiration, you should then have a look at what the author of the Scroll Position Highlight extension has done (specially from 1.5 to 1.7) to make it compatible with private browsing.
Keep up the good work!

**Comment by PerfectSlayer** [comment]
You're welcome @quiproquo 
Here is [the PR I submit to Mozilla](https://github.com/mozilla/addon-sdk/pull/2049). It will take time to be validated and integrated to Firefox.

Thanks for pointing me the Scroll Position Highlight addon but this addon doesn't use the bogus ```sdk/windows``` API I use.

**Comment by PerfectSlayer** [comment]
As the submission process should use bugzilla, the progress of the bug could be followed [on the bug itself](https://bugzilla.mozilla.org/show_bug.cgi?id=1224863).

**Comment by PerfectSlayer** [comment]
Hi @quiproquo,
The patch has been accepted and will be added to the release train.
So it will be available for Firefox 51 :sweat_smile: 

If you enjoy my work and are the original bug reporter on AMO, please consider rating 5 stars as all your wishes about the addon will be granted in the coming months :wink:

**Comment by quiproquo** [comment]
Great news indeed, just can't wait for FX51!
There are a couple of other extensions which may benefit from that patch.
Yeah, am going to rate it to the top on AMO right now...

**Comment by Gitoffthelawn** [comment]
Fantastic job Bruce!

For reference, here is a link to the bugzilla issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1224863
