### ISSUE TITLE
Copying from address bar issue

### ISSUE THREAD

**Issue by atomGit** [PerfectSlayer/scrollupfolder#38]
FF 48 on Mint

minor glitch - if you use the mouse wheel to move up a directory, but do not load the new URL, and then copy the URL, the previous URL is copied instead of the shorter one

**Comment by PerfectSlayer** [comment]
Hi @atomGit,

First, thanks for you issue (not the first one! :sweat_smile:)
I already saw this issue and I got stuck on the _copyController of urlbar.

If you want more explanations, there is some specific behaviors added when you copy the URL from urlbar:

- [The copy controller implementation](https://dxr.mozilla.org/mozilla-beta/rev/49788f46f9b6ffb93bb524556f59b20aa2c7dc8a/browser/base/content/urlbarBindings.xml#655)
- [The function which gets text to copy](https://dxr.mozilla.org/mozilla-beta/rev/49788f46f9b6ffb93bb524556f59b20aa2c7dc8a/browser/base/content/urlbarBindings.xml#585)
- [And some other event bindings on urlbar…](https://dxr.mozilla.org/mozilla-beta/rev/49788f46f9b6ffb93bb524556f59b20aa2c7dc8a/browser/base/content/browser.xul#698)

So I'm looking how to deal with them. I'll come back to you when I found a solution.

**Comment by PerfectSlayer** [comment]
Ok, I found a way to start « edit mode » when changing urlbar location. So the copy action works fine now.

I will test it some days before making a new release (to be sure no bugs were added…).
I also saw you have a fork. So could you test the last version of the master and check if everything is okay for you? (Or I could upload you a non-signed version if you prefer?)

**Comment by atomGit** [comment]
if you'd like me to test the new build, i'd be happy to do so

> I also saw you have a fork.

no sir! learning JS is sort of on my 'to-do' list, but i have writ nothing in it thus far

**Comment by PerfectSlayer** [comment]
Hi @atomGit,

I build a beta release to test. Keep in mind it was not signed so it could only run on a [developer edition of Firefox](https://www.mozilla.org/firefox/developer/). Here it is: [scrollupfolder-5.3.0-beta1.zip](https://github.com/PerfectSlayer/scrollupfolder/files/491521/scrollupfolder-5.3.0-beta1.zip).

Thanks for your feedback!
Regards.

**Comment by atomGit** [comment]
i'm running the beta now - will let you know if there's any issues, bot 
so far it's working fine

**Comment by PerfectSlayer** [comment]
Hi @atomGit,
I plan to make the release in two days (next thursday).
If you found any issue, please let me know.

**Comment by atomGit** [comment]
no issues here - go for it!

**Comment by PerfectSlayer** [comment]
Hum, it's been one year now since your feedback and I still not have release the fix!? What happened to me? 
Sorry for the delay! 🙏  I planned to release it the next month with an update about the WebExtension issue #40

**Comment by atomGit** [comment]
thanks for the update :)

i'm still running 5.2.1 which is the beta i guess, so no problems here

**Comment by PerfectSlayer** [comment]
Finally, [the add-on was released on AMO](https://addons.mozilla.org/en-US/firefox/addon/scroll-up-folder/). The update should land soon in your browser.
Thanks for your patience! 😇
