### ISSUE TITLE
atomGit/scrollupfolder

### ISSUE THREAD

**Issue by atomGit** [PerfectSlayer/scrollupfolder#39]
i'm curious about this fork - https://github.com/atomGit/scrollupfolder - which is apparently in my name - just curious as to why it's my name

i don't know much about how github works, so maybe i forked it myself accidentally? LOL

if so, let me know and i'll delete it

**Comment by PerfectSlayer** [comment]
Hi @atomGit 

It looks like you finally found a way to remove you fork 😉
